# Generated by Django 4.2.7 on 2024-10-21 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=14)),
                ('address', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'Um business com esse celular já foi cadastrado.'}, max_length=15, null=True, unique=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('general_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'BusinessPlural',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('profile_picture', models.URLField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('approximateDate', models.DateField()),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
