# Generated by Django 4.2.7 on 2024-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approximateDate',
            field=models.DateTimeField(),
        ),
    ]
